# Generated by Django 3.1.4 on 2020-12-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='rank',
            field=models.IntegerField(default=100),
        ),
    ]
